controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\forms\InvoiceForm;
use app\models\forms\LoginForm;
use app\models\forms\TransferForm;
use app\models\Invoice;
use app\models\Transfer;
use app\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error'   => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class'           => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $query = User::find();

        $dataProvider = new ActiveDataProvider([
            'query'      => $query,
            'pagination' => [
                'defaultPageSize' => 20,
                'totalCount'      => $query->count(),
            ],
        ]);

        return $this->render('index',
            ['dataProvider' => $dataProvider]
        );
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('account');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAccount()
    {
        $query = Invoice::find()
            ->where(['and',
                ['user_to_id' => Yii::$app->user->id],
                ['status' => Invoice::STATUS_NEW]])->count();
        if (0 != $query) {
            Yii::$app->session->setFlash('info', 'You have some NEW incoming invoices.');
            return $this->redirect('invoice');
        }

        return $this->redirect('transfer');
    }

    public function actionTransfer()
    {
        $model = new TransferForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                if ($model->transfer()) {
                    Yii::$app->session->setFlash('success', 'Transfer success.');
                } else {
                    Yii::$app->session->setFlash('danger', 'Something go wrong!!!');
                }

                return $this->redirect(['transfer']);
            }
        }

        $query = Transfer::find()
            ->where(['or',
                ['user_from_id' => Yii::$app->user->id],
                ['user_to_id' => Yii::$app->user->id]]);

        $dataProvider = new ActiveDataProvider([
            'query'      => $query,
            'sort'       => [
                'defaultOrder' => ['send_time' => SORT_DESC],
                'attributes'   => ['send_time', 'amount', 'user_to_id', 'user_from_id'],
            ],
            'pagination' => [
                'defaultPageSize' => 5,
                'totalCount'      => $query->count(),
            ],
        ]);

        return $this->render('transfer', [
            'model'        => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionInvoice()
    {
        Invoice::updateAll(['status' => Invoice::STATUS_WAIT],
            ['and',
                ['user_to_id' => Yii::$app->user->id],
                ['status' => Invoice::STATUS_NEW],
            ]);

        $model = new InvoiceForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                if ($model->create()) {
                    Yii::$app->session->setFlash('success', 'Invoice created.');
                } else {
                    Yii::$app->session->setFlash('danger', 'Something go wrong!!!');
                }

                return $this->redirect(['invoice']);
            }
        }

        $query = Invoice::find()
            ->where(['user_to_id' => Yii::$app->user->id]);

        $getingInvoiceDataProvider = new ActiveDataProvider([
            'query'      => $query,
            'sort'       => [
                'defaultOrder' => ['created_at' => SORT_DESC],
                'attributes'   => ['created_at', 'updated_at', 'amount', 'user_from_id', 'user_from_id'],
            ],
            'pagination' => [
                'defaultPageSize' => 5,
                'totalCount'      => $query->count(),
            ],
        ]);

        $query = Invoice::find()
            ->where(['user_from_id' => Yii::$app->user->id]);

        $sendingInvoiseDataProvider = new ActiveDataProvider([
            'query'      => $query,
            'sort'       => [
                'defaultOrder' => ['created_at' => SORT_DESC],
                'attributes'   => ['created_at', 'updated_at', 'amount', 'user_to_id', 'user_from_id'],
            ],
            'pagination' => [
                'defaultPageSize' => 5,
                'totalCount'      => $query->count(),
            ],
        ]);

        return $this->render('invoice', [
            'model'                      => $model,
            'getingInvoiceDataProvider'  => $getingInvoiceDataProvider,
            'sendingInvoiseDataProvider' => $sendingInvoiseDataProvider,
        ]);
    }
}

views/site/_account_tabs.php
<?php
use yii\bootstrap\Alert;
use yii\bootstrap\Nav;

?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
<?= Nav::widget([
    'options' => ['class' => 'nav-tabs'],
    'items' => [
        [
            'label' => 'Transfers',
            'url' => ['site/transfer'],
        ],
        [
            'label' => 'Infoices',
            'url' => ['site/invoice'],
        ]
    ]
]) ?>
</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <?php
        foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
            echo Alert::widget([
                'options' => [
                    'class' => 'alert-' . $key,
                ],
                'body' => $message,
            ]);
        }
        ?>
    </div>
</div>   

<div class="row">
    <div class="col-md-8 col-md-offset-2">
     <?= $content ?>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\grid\GridView;
$this->title = 'All Users';
?>

<div class="site-index">

    <div class="jumbotron">
        <h1>All Users</h1>

    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                    <?=GridView::widget([
                        'dataProvider' => $dataProvider,
                        'columns' => [
                            'name',
                            'balance',
                        ],
                    ])
                    ?>
            </div>
        </div>

    </div>
</div>

views/site/invoice.php
<?php

use yii\bootstrap\ActiveForm;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;

$this->title = 'Счета к оплате';
?>

<?php $this->beginContent('@app/views/site/_account_tabs.php');?>
<div class="row">
<?php Modal::begin([
    'header' => '<h3>Send Invoice</h3>',
    'id'     => 'modal',
]);
$form = ActiveForm::begin();?>

        <?=$form->field($model, 'name');?>
        <?=$form->field($model, 'amount');?>

        <div class="form-group">
            <?=Html::submitButton('Submit', [
                'class' => 'btn btn-primary',
                'data-toggle' => 'modal',
                'data-target' => '#modal'
                ]);?>
        </div>
    <?php ActiveForm::end();?>
<?php Modal::end();?>

</div>

<div class="row">   
        <h3>Create Invoice</h3>
        <?=Html::button('Send new Invoice', [
                'class'       => 'btn btn-primary',
                'data-toggle' => 'modal',
                'data-target' => '#modal',
            ]);?>
</div>
<hr>

<div class="row">

        <h3>Incoming invoices</h3>
        <?php Pjax::begin();?>
        <?=GridView::widget([
    'id'           => 'invoices-in',
    'dataProvider' => $getingInvoiceDataProvider,
    'columns'      => [
        'id',
        'user_from_id',
        'amount',
        'created_at',
        'updated_at',
        [
            'attribute' => 'status',
            'value'     => function ($model) {
                return $model->status;
            },
        ],
        [
            'header'         => 'Actions',
            'class'          => ActionColumn::className(),
            'template'       => '{accept} {reject}',
            'controller'     => 'invoice',
            'buttons'        => [
                'accept' => function ($url) {
                    return Html::a('Accept', $url, ['class' => 'btn btn-primary btn-xs', 'data-method' => 'post']);
                },
                'reject' => function ($url) {
                    return Html::a('Reject', $url, ['class' => 'btn btn-danger btn-xs', 'data-method' => 'post']);
                },
            ],
            'visibleButtons' => [
                'accept' => function ($model) {
                    return $model->isStatusWait();
                },
                'reject' => function ($model) {
                    return $model->isStatusWait();
                },
            ],
        ],
    ],
]);?>
        <?php Pjax::end();?>

</div>
<div class="row">
        <h3>Sending invoices</h3>
        <?php Pjax::begin();?>
        <?=GridView::widget([
    'id'           => 'invoices-out',
    'dataProvider' => $sendingInvoiseDataProvider,
    'columns'      => [
        'created_at:datetime',
        [
            'attribute' => 'user_to_id',
            'value'     => function ($model) {
                return $model->userTo->name;
            },
        ],
        'amount',
        [
            'attribute' => 'status',
            'value'     => function ($model) {
                return $model->status;
            },
        ],
    ],
]);?>
        <?php Pjax::end();?>
</div>

<?php $this->endContent();?>

views/site/login.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title                   = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?=Html::encode($this->title);?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="user-login">

    <?php $form = ActiveForm::begin([
    'id'          => 'login-form',
    'options'     => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ],
]);?>

        <?=$form->field($model, 'name');?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?=Html::submitButton('Submit', ['class' => 'btn btn-primary']);?>
            </div>
        </div>
    <?php ActiveForm::end();?>

</div>
    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>any</strong> <em>Name</em>.<br>
        If it`s not exist, it`ll be registered automaticly.
    </div>
</div>

views/site/transfer.php
<?php

use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $this->beginContent('@app/views/site/_account_tabs.php');?>
<div class="row">
<?php Modal::begin([
    'header' => '<h3>New Transfer</h3>',
    'id'     => 'modal',
]);
$form = ActiveForm::begin();?>

        <?=$form->field($model, 'name');?>
        <?=$form->field($model, 'amount');?>

        <div class="form-group">
            <?=Html::submitButton('Submit', ['class' => 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => '#modal']);?>
        </div>
    <?php ActiveForm::end();?>
<?php Modal::end();?>

</div>

<div class="row">
        <h3>Transfers history</h3>
        <?=Html::button('Create new Transfer', [
                'class'       => 'btn btn-primary',
                'data-toggle' => 'modal',
                'data-target' => '#modal',
            ]);?>
            <hr>
        <?=GridView::widget([
                'dataProvider' => $dataProvider,
                'columns'      => [
                    'id',
                [
            'attribute' => 'user_from_id',
            'value'     => function ($model) {
                return $model->userFrom->name;
            },
        ],
        [
            'attribute' => 'user_to_id',
            'value'     => function ($model) {
                return $model->userTo->name;
            },
        ],
        'amount',
        'send_time:datetime',
    ],
]);?>
</div>
<?php $this->endContent();?>